export enum ActionType {
  //login
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",

  // signout
  SIGN_OUT = "SIGN_OUT",

  // get all employees
  GET_ALL_EMPLOYEES_REQUEST = "GET_ALL_EMPLOYEES_REQUEST",
  GET_ALL_EMPLOYEES_SUCCESS = "GET_ALL_EMPLOYEES_SUCCESS",
  GET_ALL_EMPLOYEES_FAIL = "GET_ALL_EMPLOYEES_FAIL",

  // eDit specific employee
  EDIT_SPECIFIC_EMPLOYEE_REQUEST = "EDIT_SPECIFIC_EMPLOYEE_REQUEST",
  EDIT_SPECIFIC_EMPLOYEE_SUCCESS = "EDIT_SPECIFIC_EMPLOYEE_SUCCESS",
  EDIT_SPECIFIC_EMPLOYEE_FAIL = "EDIT_SPECIFIC_EMPLOYEE_FAIL",

  // conversations
  GET_ALL_CONVERSATIONS_REQUEST = "GET_ALL_CONVERSATIONS_REQUEST",
  GET_ALL_CONVERSATIONS_SUCCESS = "GET_ALL_CONVERSATIONS_SUCCESS",
  GET_ALL_CONVERSATIONS_FAIL = "GET_ALL_CONVERSATIONS_FAIL",

  //edit specific conversation
  EDIT_SPECIFIC_CONVERSATION_REQUEST = "EDIT_SPECIFIC_CONVERSATION_REQUEST",
  EDIT_SPECIFIC_CONVERSATION_SUCCESS = "EDIT_SPECIFIC_CONVERSATION_SUCCESS",
  EDIT_SPECIFIC_CONVERSATION_FAIL = "EDIT_SPECIFIC_CONVERSATION_FAIL",

  // make new conversation
  MAKE_NEW_CONVERSATION_REQUEST = "MAKE_NEW_CONVERSATION_REQUEST",
  MAKE_NEW_CONVERSATION_SUCCESS = "MAKE_NEW_CONVERSATION_SUCCESS",
  MAKE_NEW_CONVERSATION_FAIL = "MAKE_NEW_CONVERSATION_FAIL",

  // inner company conversations
  GET_ALL_INNER_CONVERSATIONS_REQUEST = "GET_ALL_INNER_CONVERSATIONS_REQUEST",
  GET_ALL_INNER_CONVERSATIONS_SUCCESS = "GET_ALL_INNER_CONVERSATIONS_SUCCESS",
  GET_ALL_INNER_CONVERSATIONS_FAIL = "GET_ALL_INNER_CONVERSATIONS_FAIL",

  // edit inner specific conversation
  EDIT_SPECIFIC_INNER_CONVERSATION_REQUEST = "EDIT_SPECIFIC_INNER_CONVERSATION_REQUEST",
  EDIT_SPECIFIC_INNER_CONVERSATION_SUCCESS = "EDIT_SPECIFIC_INNER_CONVERSATION_SUCCESS",
  EDIT_SPECIFIC_INNER_CONVERSATION_FAIL = "EDIT_SPECIFIC_INNER_CONVERSATION_FAIL",

  // make new Inner compnay conversation
  MAKE_NEW_COMPANY_CHAT_REQUEST = "MAKE_NEW_COMPANY_CHAT_REQUEST",
  MAKE_NEW_COMPANY_CHAT_SUCCESS = "MAKE_NEW_COMPANY_CHAT_SUCCESS",
  MAKE_NEW_COMPANY_CHAT_FAIL = "MAKE_NEW_COMPANY_CHAT_FAIL",

  // remove mentions
  REMOVE_FROM_MENTIONS = "REMOVE_FROM_MENTIONS",

  // remove from participants
  REMOVE_FROM_PARTICIPANTS = "REMOVE_FROM_PARTICIPANTS",
}
